[owner]
name = "podmaker"
email = "admin@podmaker.dev"

[s3]
access_key = "123"
access_secret = "456"
bucket = "podmake"
endpoint = "https://s3.amazonaws.com"
# must be public-read
cdn_prefix = "https://s3.amazonaws.com"