[app]
# running mode, "oneshot" or "watch"
# - oneshot: generate the feed and exit
# - watch: generate the feed and watch for changes
mode = "oneshot"

# level of logging, "DEBUG", "INFO", "WARNING", "ERROR"
loglevel = "INFO"

# optional, the admin of the feed
[owner]
name = "podmaker"
email = "admin@podmaker.dev"

[s3]
access_key = "123"
access_secret = "456"
bucket = "podmake"
endpoint = "https://s3.amazonaws.com/"
# must be public-read
cdn_prefix = "https://s3.amazonaws.com/"

# notice: the sources is an array, it must specify using `[[]]`
[[sources]]
# used to generate the feed url, must be unique, prefer to use numbers, letters, space and underscores
id = "source_1"
# the url of the source
url = "https://example.com/source_1/"

[[sources]]
id = "source_2"
url = "https://example.com/source_2/"