[app]
mode = "oneshot"
loglevel = "INFO"

[owner]
# optional
name = "podmaker"
email = "admin@podmaker.dev"

[s3]
access_key = "123"
access_secret = "456"
bucket = "podmake"
endpoint = "https://s3.amazonaws.com/"
# must be public-read
cdn_prefix = "https://s3.amazonaws.com/"

[[sources]]
# used to generate the feed url
id = "source_1"
# the url of the source
url = "https://example.com/source_1/"

[[sources]]
id = "source_2"
url = "https://example.com/source_2/"